amcl:
  ros__parameters:
    use_sim_time: True
    # 我们不启动AMCL，但预留配置防报错

bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    default_bt_xml_filename: "navigate_to_pose_w_replanning_and_recovery.xml" # nav2预设的， 带重规划和恢复机制的默认树

behavior_server:
  ros__parameters:
    use_sim_time: True
    local_costmap_name: local_costmap
    global_costmap_name: global_costmap
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    robot_radius: 0.175
    local_frame: odom
    global_frame: map
    robot_base_frame: base_link
    cycle_frequency: 10.0
    # 声明所有的行为插件别名
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]

    # 1. 原地旋转（用于重新扫描周围环境）
    spin:
      plugin: "nav2_behaviors/Spin"
      max_rotational_vel: 1.0     # 限制原地转圈的最大速度
      min_rotational_vel: -1.0
      rotational_acc_lim: 1.0     # 转圈加速度

    # 2. 盲退（在卡死时往后退一点点）
    backup:
      plugin: "nav2_behaviors/BackUp"
      max_speed: 0.15             # 倒车最大速度 (m/s)
      min_speed: -0.15
      acc_lim_x: 0.5              # 倒车加速度

    # 3. 沿特定航向行驶
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
      max_speed: 0.15
      min_speed: -0.15
      acc_lim_x: 0.5

    # 4. 原地等待（等动态障碍物走开）
    wait:
      plugin: "nav2_behaviors/Wait"

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]
    # 1. 定义进度检查器 (防止小车卡在原地不动)
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    # 2. 定义目标检查器 (这正是刚才报错缺失的部分！)
    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25  # 到达目标的 X/Y 允许误差(米)
      yaw_goal_tolerance: 0.25 # 到达目标的角度允许误差(弧度)
      stateful: True

    # 3. 使用 DWB 局部规划器
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      # ====== 小车运动学参数 ======
      max_vel_x: 0.6        # 最大前进速度 (m/s)
      min_vel_x: 0.0        # 最小前进速度 (不允许倒车，倒车由 behavior 负责)
      max_vel_y: 0.0        # 最大侧向速度 (差速轮不能横行，必须为0)
      min_vel_y: 0.0        # 最小侧向速度
      max_vel_theta: 1.0    # 最大原地旋转角速度 (rad/s)
      min_vel_theta: -1.0   # 最小旋转角速度
      min_speed_xy: 0.0
      max_speed_xy: 0.3
      min_speed_theta: 0.0

      acc_lim_x: 0.3       # X方向最大加速度
      acc_lim_y: 0.0        # Y方向最大加速度
      acc_lim_theta: 2.0    # 旋转最大加速度
      decel_lim_x: -0.3     # X方向最大减速度
      decel_lim_y: 0.0      # Y方向最大减速度
      decel_lim_theta: -2.0 # 旋转最大减速度

      vx_samples: 20        # X方向采样20条轨迹
      vy_samples: 1         # Y方向采样1条 (因为不能横走)
      vtheta_samples: 20    # 旋转采样20条轨迹
      sim_time: 1.5         # 每次向前预测 1.5 秒的轨迹
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.scale: 62.0   # 避障权重
      PathAlign.scale: 32.0      # 贴合路径权重
      GoalAlign.scale: 24.0      # 对齐目标权重
      PathDist.scale: 32.0       # 距离路径权重
      GoalDist.scale: 24.0       # 距离目标权重
      RotateToGoal.scale: 32.0   # 原地旋转对齐权重
      Oscillation.scale: 1.0     # 防止小车来回抖动的权重

planner_server:
  ros__parameters:
    use_sim_time: True
    tolerance: 0.5
    use_astar: true
    planner_plugins: ["GridBased"]
    # 使用新一代的 SmacPlanner2D
    GridBased:
      plugin: "nav2_smac_planner/SmacPlanner2D"
      allow_unknown: true    # 允许规划器将路径穿过尚未建图的未知区域
      tolerance: 0.5               # Smac 自己也需要这个容忍度参数
      use_final_approach_orientation: true # 到达终点时平滑转向
      downsample_costmap: false    # 不降采样，保证精度

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: True
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      robot_radius: 0.175 # TB4近似轮廓
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          min_obstacle_height: 0.15   # 忽略距离地面 15 厘米以下的障碍物（防止扫到地板）
          obstacle_range: 4.5        # 在这个范围内发现障碍物，就标记在代价地图上
          raytrace_range: 5.0        # 在这个范围内如果没有扫到障碍物，就清除该区域的代价值
          min_obstacle_range: 0.2   # Nav2 不处理太近的噪点
          clearing: True
          marking: True
          data_type: "LaserScan"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.3 # 膨胀半径，防撞墙

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: True
      global_frame: map
      robot_base_frame: base_link
      use_maximum: true
      robot_radius: 0.175
      resolution: 0.05
      track_unknown_space: true       # 追踪未知区域
      always_send_full_costmap: true  # 确保代价地图完整下发
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        map_topic: /map # 必须与 RTAB-Map 输出的地图话题一致
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.3